#!/bin/bash
set -e

OPENFIRE_VERSION=3.9.3
if [ -f /app/setup/openfire_${OPENFIRE_VERSION}_all.deb ]; then
	dpkg -i /app/setup/openfire_${OPENFIRE_VERSION}_all.deb
else
	wget "http://www.igniterealtime.org/downloadServlet?filename=openfire/openfire_${OPENFIRE_VERSION}_all.deb" -O /tmp/openfire_${OPENFIRE_VERSION}_all.deb
	dpkg -i /tmp/openfire_${OPENFIRE_VERSION}_all.deb
	rm -rf openfire_${OPENFIRE_VERSION}_all.deb
fi

cat > /etc/supervisor/conf.d/openfire.conf <<EOF
[program:openfire]
priority=20
directory=/var/lib/openfire
command=/usr/bin/java
	-server
	-DopenfireHome=/usr/share/openfire
	-Dopenfire.lib.dir=/usr/share/openfire/lib
	-classpath /usr/share/openfire/lib/startup.jar
	-jar /usr/share/openfire/lib/startup.jar
user=openfire
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s_error.log
EOF
