#!/bin/bash

set -e

OPENFIRE_VERSION=3.9.1
if [ -f /openfire/setup/openfire_${OPENFIRE_VERSION}_all.deb ]; then
	dpkg -i /openfire/setup/openfire_${OPENFIRE_VERSION}_all.deb
else
	wget "http://www.igniterealtime.org/downloadServlet?filename=openfire/openfire_${OPENFIRE_VERSION}_all.deb" -O /tmp/openfire_${OPENFIRE_VERSION}_all.deb
	dpkg -i /tmp/openfire_${OPENFIRE_VERSION}_all.deb
	rm -rf openfire_${OPENFIRE_VERSION}_all.deb
fi

mkdir -p /var/run/sshd
cat > /etc/supervisor/conf.d/sshd.conf <<EOF
[program:sshd]
directory=/
command=/usr/sbin/sshd -D
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s_error.log
EOF
